// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsB6gJg_hnXKKKLBCm4u_NqaKEeUtvXsg',
    appId: '1:429921227436:web:7ba65bb3ec88d462894509',
    messagingSenderId: '429921227436',
    projectId: 'gramseva-11066',
    authDomain: 'gramseva-11066.firebaseapp.com',
    storageBucket: 'gramseva-11066.firebasestorage.app',
    measurementId: 'G-T6TBDWTSCN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWnwFUQbOPsPv_WnBU77ku2Z2HtwrCQk0',
    appId: '1:429921227436:android:95757ada8444a162894509',
    messagingSenderId: '429921227436',
    projectId: 'gramseva-11066',
    storageBucket: 'gramseva-11066.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsQybN0-nPrxOaX9wpJhp3DAkJSj37wV8',
    appId: '1:429921227436:ios:99cbcc07ee229a7b894509',
    messagingSenderId: '429921227436',
    projectId: 'gramseva-11066',
    storageBucket: 'gramseva-11066.firebasestorage.app',
    iosBundleId: 'com.example.gramSeva',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsQybN0-nPrxOaX9wpJhp3DAkJSj37wV8',
    appId: '1:429921227436:ios:99cbcc07ee229a7b894509',
    messagingSenderId: '429921227436',
    projectId: 'gramseva-11066',
    storageBucket: 'gramseva-11066.firebasestorage.app',
    iosBundleId: 'com.example.gramSeva',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsB6gJg_hnXKKKLBCm4u_NqaKEeUtvXsg',
    appId: '1:429921227436:web:24d20d7aa0e9569f894509',
    messagingSenderId: '429921227436',
    projectId: 'gramseva-11066',
    authDomain: 'gramseva-11066.firebaseapp.com',
    storageBucket: 'gramseva-11066.firebasestorage.app',
    measurementId: 'G-MCV3TKPRS9',
  );
}
